### ISSUE TITLE
ValueError: not enough values to unpack (expected 1, got 0)

### ISSUE THREAD

**Issue by forderud** [vpelletier/python-functionfs#15]
Sorry for asking a newbie question, but I'm struggling to get started with `functionfs` on my Raspberry Pi 4 B that is supposed to have a UDC.

Steps performed:
* Install latest Raspberry Pi OS with Linux 5.4.83.
* Connect Pi to a different computer through the USB-C connector.
* `sudo pip3 install functionfs` to install functionfs 0.5.0
* Download `examples/hid/device.py` script from this repo
* `sudo modprobe libcomposite`
* ~~`sudo setcap cap_sys_admin+ep device.py` (don't know if this is correct)~~
* Attempt to run device.py:
```
pi@raspberrypi:~/Desktop $ sudo python3 device.py
Traceback (most recent call last):
  File "device.py", line 144, in <module>
    main()
  File "device.py", line 133, in main
    'manufacturer': 'python-functionfs',
  File "/usr/local/lib/python3.7/dist-packages/functionfs/gadget.py", line 469, in __init__
    **kw
  File "/usr/local/lib/python3.7/dist-packages/functionfs/gadget.py", line 149, in __init__
    udc, = os.listdir(self.class_udc_path)
ValueError: not enough values to unpack (expected 1, got 0)
```

I've also tested passing `--username pi` as argument, but the error is still the same. I see there's also a `--udc` argument, but don't really know what to pass here. USB gadgets is totally new to me, so I don't really know how to proceed.

**Comment by vpelletier** [comment]
This error means you do not have any UDC (USB Device Controller) available - which, as I indeed believe the 4B has one on its USB-C port, means the corresponding module is not loaded.

An easy way to confirm this is to look into `/sys/class/udc`: if there is nothing, no UDC module is loaded. If there is one symlink, then my code will use this UDC. If there are more than one (which is likely quite rare), then the `--udc` argument is needed to tell which one to use. Here is how it looks on my pi zero with a [raspi Debian](raspi.debian.net/):

```
$ ls -l /sys/class/udc/
total 0
lrwxrwxrwx 1 root root 0 Jan  1  1970 20980000.usb -> ../../devices/platform/soc/20980000.usb/udc/20980000.usb
```

If Linux did not load the module, it probably means the pi's devicetree did not enable it. How to enable it will depend on how your devicetree is managed. I believe Raspbian has a config tool to select which features should be enabled, which is typically used to enable some pins on the GPIO connector, but should also be able to enable the UDC in the devicetree.

In my case the module handling this UDC is the kernel.org dwc2, but I believe there may be another module for it in custom kernels like used in raspbian (I have not tried it for years, so this may be out-of-date).

**Comment by forderud** [comment]
Thanks for very useful feedback @vpelletier  :+1:  I've now managed to get one step further by enabling `dwc2` through the following system config tweaks:
* `echo "dtoverlay=dwc2" >> /boot/config.txt`
* `echo "dwc2" >> /etc/modules`

This gives the following after a reboot:
```
pi@raspberrypi:~ $ ls -l /sys/class/udc
total 0
lrwxrwxrwx 1 root root 0 Feb 27 14:38 fe980000.usb -> ../../devices/platform/soc/fe980000.usb/udc/fe980000.usb
```

However, the functionfs sample script is still failing for me:
```
pi@raspberrypi:~/Desktop $ sudo python3 device.py 
Traceback (most recent call last):
  File "device.py", line 144, in <module>
    main()
  File "device.py", line 133, in main
    'manufacturer': 'python-functionfs',
  File "/usr/local/lib/python3.7/dist-packages/functionfs/gadget.py", line 473, in __enter__
    super(GadgetSubprocessManager, self).__enter__()
  File "/usr/local/lib/python3.7/dist-packages/functionfs/gadget.py", line 254, in __enter__
    self.__enter()
  File "/usr/local/lib/python3.7/dist-packages/functionfs/gadget.py", line 273, in __enter
    dir=self.udb_gadget_path,
  File "/usr/lib/python3.7/tempfile.py", line 505, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/config/usb_gadget/g_t7oz2s34'
```

**Comment by forderud** [comment]
Closing, since my problem have been resolved. Thanks for sharing this great project :-)
