### ISSUE TITLE
`use_2to3` removed in setuptools 58+

### ISSUE THREAD

**Issue by dogtopus** [vpelletier/python-functionfs#21]
This breaks the installation since `setup.py` currently requires it.

**Comment by vpelletier** [comment]
Thanks for the report. This should be fixed by 2c8201da99d4024381ca7bda7913cb8a20238ea8 . I intend to keep this report open until I make a pypi release (which should be soon).

**Comment by vpelletier** [comment]
This fix is now released as part of 0.6.0 . Thanks again !
